# docker-compose -f rolweb/docker-compose.yml -f docker-compose.yml up -d

services:
  api:
    build: ../roldndapi
    ports:
      - "81:3000"
    volumes:
      - ../roldndapi:/app
    # command: ["sleep", "infinity"]
